name: flick_video_player
description: Flick Video Player is a video player for flutter. The video_player plugin gives low level access for the video playback.
repository: https://github.com/GeekyAnts/flick-video-player
homepage: https://github.com/GeekyAnts/flick-video-player

version: 0.1.1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: 0.11.1+2
  provider: ^4.1.3
  wakelock: ^0.1.4+1
  # For passing flags to the underlying Android window manager
  flutter_windowmanager: ^0.0.2
  subtitle_wrapper_package:
        git:
            url: https://github.com/ayush221b/flutter_subtitle_wrapper.git
            ref: 7b82c86c5333339b0911b5379f74016b570a885a

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
